services:
  wordpress:
    image: arm64v8/wordpress:latest
    container_name: wordpress
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: arm64v8/mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    image: php:8.1-fpm
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
